    <div class="container body">
      <div class="main_container">

        <!-- 左侧边栏 start -->
        <div class="col-md-3 left_col">
          <!-- 左侧边栏上班部分 start -->
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>云之讯</span></a>
            </div>

            <div class="clearfix"></div>

            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="/image/common/logo.png" alt="logo" class="img-circle profile_img">
              </div>
              <div class="profile_info"  style="text-align: center;">
                <span>欢迎登录云之讯</span>
                <h2><?php //echo $adminUser->getUsername();?></h2>
              </div>
            </div>
            <br />
            <!-- 左侧边栏上班部分 end-->
            
            <!-- 索引sidebar start -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li>
                    <a href="/"><i class="fa fa-home"></i> 首页 <span class="fa"></span></a>
                  </li>
                  <li>
                    <a href="/index/template/index"><i class="fa fa-home"></i>模板管理</a>
                  </li>
                  <li>
                    <a><i class="fa fa-home"></i> 平台短信 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/index/send/index">短信发送</a></li>
                      <li><a href="/index/send/sendtask">发送任务</a></li>
                      <li><a href="/index/send/data">数据统计</a></li>
                      <li><a href="/index/send/sendrecord">发送记录</a></li>
                    </ul>
                  </li>
                  <li>
                    <a href="/index/document"><i class="fa fa-home"></i> 开发文档 <span class="fa"></span></a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- 索引sidebar end -->
          </div>
        </div>