<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>云之讯API文档</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                <h4>1.验证码短信发送</h4>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>(1)请求地址：域名/index/api/sms(注意：为了确保数据隐私和安全，用户需要通过Https Post方式请求，消息格式：json表达式。)</h5>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>(2)请求数据：</h5>
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>属性</th>
                        <th>类型</th>
                        <th>约束</th>
                        <th>说明</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <tr>
                        <td>account</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>帐号，6位， 如：a00012,b00012</td>
                      </tr>
                      <tr>
                        <td>password</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>密码，用户账户密码</td>
                      </tr>
                      <tr>
                        <td>mobile</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>发送手机号码， 国内短信不要加前缀，国际短信号码前须带相应的国家区号，如日本：0081， 不支持多号码。 国内手机号码如：18612341234 国际号码如：0085265656565</td>
                      </tr>
                      <tr>
                        <td>sign</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>签名，2-12个字（包括英文字母）</td>
                      </tr>
                      <tr>
                        <td>content</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信内容，UTF-8编码， 短信内容最长500个字（包括英文字母），其中签名2-12个字（包括英文字母）</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>(3)响应：</h5>
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>属性</th>
                        <th>类型</th>
                        <th>约束</th>
                        <th>说明</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <tr>
                        <td>status</td>
                        <td>Bool</td>
                        <td>必选</td>
                        <td>短信发送状态</td>
                      </tr>
                      <tr>
                        <td>code</td>
                        <td>Int</td>
                        <td>必选</td>
                        <td>短信请求响应返回码， 参考“请求响应返回码”定义的返回码 （详见第九章第1节）</td>
                      </tr>
                      <tr>
                        <td>msg</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信请求响应返回中文描述， 参考“请求响应返回码”定义的中文描述 （详见第九章第1节）</td>
                      </tr>
                      <tr>
                        <td>data</td>
                        <td>Array</td>
                        <td>必选</td>
                        <td>发送成功才返回的数据</td>
                      </tr>
                      <tr>
                        <td>content</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信内容，包含签名</td>
                      </tr>
                      <tr>
                        <td>send_time</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>发送时间</td>
                      </tr>
                      <tr>
                        <td>sid</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信标识符（用于匹配状态报告）， 一个手机号对应一个sid</td>
                      </tr>
                      <tr>
                        <td>mobile</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>接收短信的手机号码</td>
                      </tr>
                      <tr>
                        <td>fee</td>
                        <td>Int</td>
                        <td>必选</td>
                        <td>成功发送的短信计费条数， 计费规则如下： 70个字一条，超出70个字时按每67字一条计费 （英文按字母个数计算）</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 col-lg-12 col-sm-12">
                <h4>2.短信发送回调</h4>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>注意：短信回调需用户自己写好回调接口，然后联系管理员，将回调地址告诉管理员。</h5>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>(1)请求数据：</h5>
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>属性</th>
                        <th>类型</th>
                        <th>约束</th>
                        <th>说明</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <tr>
                        <td>sid</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信标识符（用于匹配状态报告）， 一个手机号对应一个sid</td>
                      </tr>
                      <tr>
                        <td>mobile</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>发送手机号</td>
                      </tr>
                      <tr>
                        <td>report_status</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>发送结果报告</td>
                      </tr>
                      <tr>
                        <td>arrive_time</td>
                        <td>String</td>
                        <td>必选</td>
                        <td>短信到达时间</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="col-md-12 col-lg-12 col-sm-12">
                  <h5>(2)响应：</h5>
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>属性</th>
                        <th>类型</th>
                        <th>约束</th>
                        <th>说明</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <tr>
                        <td>receive_status</td>
                        <td>Bool</td>
                        <td>必选</td>
                        <td>回调处理结果是否成功（true || false）</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<?php $this->display("public/footer.phtml"); ?>