<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>数据统计</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-10">
                    <form class="search-form">
                      <span>短信类型</span>
                      <label>
                        <select class="form-control input-sm" name="sendTypes">
                            <?php foreach ($this->sendTypes as $key =>$value):?>
                              <option value="<?php echo $key;?>" <?php echo $key==$this->type?'selected':'';?>><?php echo $value;?></option>
                            <?php endforeach;?>
                        </select>
                      </label>
                      <div class="input-prepend input-group">
                        <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                        <input type="text" style="width: 200px" name="time" id="reservation" class="form-control" value="">
                      </div>
                      <button class="btn btn-primary btn-sm" type="submit">搜索</button>
                    </form>
                  </div>
                  <div class="col-sm-2">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm" id="selectPage">
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>日期</th>
                          <th>短信类型</th>
                          <th>提交条数</th>
                          <th>计费条数</th>
                          <th>成功条数</th>
                          <th>未知条数</th>
                          <th>失败条数</th>
                        </tr>
                      </thead>
                    <?php if(!empty($this->data)):?>
                        <?php foreach ($this->data as $key=>$value):?>
                            <tbody>
                                <tr>
                                    <td style="line-height: 34px"><?php echo $key;?></td>
                                    <td style="line-height: 34px"><?php echo $this->sendTypes[$this->type];?></td>
                                    <td style="line-height: 34px"><?php echo $value['total'];?></td>
                                    <td style="line-height: 34px"><?php echo $value['fee'];?></td>
                                    <td style="line-height: 34px"><?php echo $value['success'];?></td>
                                    <td style="line-height: 34px"><?php echo $value['not_arrive'];?></td>
                                    <td style="line-height: 34px"><?php echo $value['fail'];?></td>
                                </tr>
                            </tbody>
                        <?php endforeach;?>
                      <?php else:?>
                          <tbody>
                          <tr><td colspan="16">没有找到模板</td></tr>
                          </tbody>
                      <?php endif;?>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<?php $this->display("public/footer.phtml"); ?>