<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>数据统计</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-10">
                      <span>审核状态</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                            <?php foreach ($this->templateStatus as $key =>$value):?>
                                <option value="<?php echo $key;?>" <?php echo $key==$this->status?'selected':'';?>><?php echo $value;?></option>
                            <?php endforeach;?>
                        </select>
                      </label>
                      <span>模板属性</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                        </select>
                      </label>
                      <span>模板类型</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="模板ID">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="签名">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="模板内容">
                      </label>
                      
                    <a class="btn btn-primary btn-sm">
                      搜索
                    </a>
                  </div>
                  <div class="col-sm-2">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>模板ID</th>
                          <th>模板属性</th>
                          <th>模板类型</th>
                          <th>模板内容</th>
                          <th>短信签名</th>
                          <th>创建时间</th>
                          <th>审核状态</th>
                          <th>原因</th>
                        </tr>
                      </thead>
                          <tbody>
                            <tr>
                              <td style="line-height: 34px">模板ID</td>
                              <td style="line-height: 34px">模板属性</td>
                              <td style="line-height: 34px">模板类型</td>
                              <td style="line-height: 34px">模板内容</td>
                              <td style="line-height: 34px">短信签名</td>
                              <td style="line-height: 34px">创建时间</td>
                              <td style="line-height: 34px">审核状态</td>
                              <td style="line-height: 34px">原因</td>
                            </tr>
                          </tbody>
                          <!-- <tbody>
                          <tr><td colspan="16">没有找到用户</td></tr>
                          </tbody> -->
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<?php $this->display("public/footer.phtml"); ?>