<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <style type="text/css">
      .none {
        display: none;
      }
    </style>
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-6">
            <h3>短信发送</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="form-horizontal form-label-left">
              <div class="form-group">
                <label class="control-label col-sm-2">发送方式</label>
                <div class="col-md-4">
                  <div class="radio col-md-2" style="padding-left: 0px; padding-right: 0px">
                    <label><input type="radio" name="type" value="1" checked>自行放送</label>
                  </div>
                  <div class="radio col-md-3" style="padding-left: 0px; padding-right: 0px">
                    <label><input type="radio" name="type" value="2">信嘉联创代发</label>
                  </div>
                </div>
              </div>
              <div id="autoBox">
                <div class="form-group">
                  <label class="control-label col-sm-2">号码池</label>
                  <div class="col-md-4">
                    <div class="radio col-md-2" style="padding-left: 0px; padding-right: 0px">
                      <label><input type="radio" name="leadtype" value="1" checked>批量导入</label>
                    </div>
                    <div class="radio col-md-2" style="padding-left: 0px; padding-right: 0px">
                      <label><input type="radio" name="leadtype" value="2">手动输入</label>
                    </div>
                  </div>
                </div>
                <div class="form-group" id="auto">
                  <label class="control-label col-sm-2">批量导入手机号</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <form enctype="multipart/form-data" id="fileinfo">
                      <input type="file" name="file" id="smsFile">
                    </form>
                  </div>
                  <a class="btn btn-primary btn-sm" href="/index/job/downtemp">下载批量导入模板</a>
                </div>
                <div class="form-group none" id="result">
                  <label class="control-label col-sm-2"><span id="fileName"></span></label>
                  <div class="col-md-4 control-label" style="text-align: left;">
                    <label>共计号码数：<span id="totalNum">0</span>个，有效号码数：<span id="useNum">0</span>个(已过滤错误号码：<span id="errNum">0</span>个，已过滤重复号码<span id="reNum">0</span>个)</label>
                  </div>
                  <a class="btn btn-primary btn-sm" id="delSmsFile">删除</a>
                </div>
                <div class="form-group none" id="manual">
                  <label class="control-label col-sm-2">输入待发送手机号</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea class="form-control" style="height: 50px" name="phoneText" id="phoneText"></textarea> 
                  </div>
                </div>
              </div>
              <div id="xinBox" class="none">
                <div class="form-group">
                  <label class="control-label col-sm-2">号码归属地：</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <input name="area" type="text" class="form-control" placeholder="请输入号码归属地">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-2">号码数量：</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <input name="quantity" type="text" class="form-control" placeholder="请输入号码数量">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">选择模板</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <form enctype="multipart/form-data" id="modleForm">
                    <input type="file" name="file" id="modleFile">
                  </form>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">短信类型</label>
                <div class="col-sm-1">
                  <select class="form-control" name="smstype">
                    <option>请选择</option>
                    <option>验证码</option>
                    <option>通知</option>
                    <option>营销</option>
                  </select>
                </div>
                <label class="control-label col-sm-1">短信签名</label>
                <div class="col-md-2">
                  <input name="sign" type="text" class="form-control" placeholder="长度为2-8个字符" id="sign">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">短信内容</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea class="form-control" style="height: 100px" name="content" id="content"></textarea> 
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">统计：</label>
                <label class="control-label col-sm-2" style="text-align: left;">内容长度计费条数:<span id="branch"></span>条 总计费条数:0条</label>
                <label class="control-label col-sm-4"><span id="num">0</span>/500</label>
              </div>
              <a class="btn btn-primary btn-sm col-sm-offset-2" id="sendBtn">发送</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/script/send/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>