<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
    <style type="text/css">
      .none {
        display: none;
      }
      .pagination-li .pagination-span-front{
        display: inline-block;
        border: 1px solid #ebebeb;
        border-right: 0px;
        height: 29px;
        width: 45px;
        vertical-align: middle;
        text-align: center;
        line-height: 29px;
        color: #919191;
        background-color: #f3f3f3;
        margin-left: 10px;
      }
      .pagination-li input.pagination-input{
        display: inline-block;
        line-height: 1.4;
        border:1px solid #ebebeb;
        background-color: #fff;
        height: 29px;
        width: 40px;
      }
      .pull-right .pagination-sm .i-height i:before{

      }
       .checkbox input.pagination-input{
        display: inline-block;
        line-height: 1.4;
        border:1px solid #ebebeb;
        background-color: #fff;
        height: 26px;
        width: 30px;
       }
       .form-group label.label-font-size{
        font-size: 14px;
       }
      .pagination-li .pagination-span-back{
        display: inline-block;
        border: 1px solid #ebebeb;
        border-left: 0px;
        height: 29px;
        width: 35px;
        vertical-align: middle;
        text-align: center;
        line-height: 29px;
        color: #919191;
        background-color: #f3f3f3;
      }
      .pagination-li a#btnJump{
        float: right;
      }
      .pagination-wrapper .dataTables_paginate a {
        background-color: #fff !important;
      }
      .pagination-wrapper .pagination>.active>a {
        color: #fff;
        background-color: #337ab7 !important;
      }
    </style>
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-6">
            <h3>短信发送</h3>
          </div>
        </div>
        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="form-horizontal form-label-left">
              <div class="form-group">
                <label class="control-label col-sm-2">发送方式</label>
                <div class="col-md-4 col-lg-6 open-user-modal">
                  <div class="radio col-md-2 col-lg-2">
                    <label><input type="radio" name="type" value="1" checked>自行放送</label>
                  </div>
                  <div class="radio col-md-3 col-lg-3">
                    <label><input type="radio" name="type" value="2">信嘉联创代发</label>
                  </div>
                </div>
              </div>
              <div id="autoBox">
                <div class="form-group">
                  <label class="control-label col-sm-2">号码池</label>
                  <div class="col-md-4 col-lg-6 open-user-modal">
                    <div class="radio col-md-2 col-lg-2">
                      <label><input type="radio" name="leadtype" value="1" checked>批量导入</label>
                    </div>
                    <div class="radio col-md-2 col-lg-3">
                      <label><input type="radio" name="leadtype" value="2">手动输入</label>
                    </div>
                  </div>
                </div>
                <div class="form-group" id="auto">
                  <label class="control-label col-sm-2">批量导入手机号</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <form enctype="multipart/form-data" id="fileinfo">
                      <input type="file" name="file" id="smsFile">
                    </form>
                  </div>
                  <a class="btn btn-primary btn-sm" href="/index/job/downtemp">下载批量导入模板</a>
                </div>
                <div class="form-group none" id="result">
                  <label class="control-label col-sm-2"><span id="fileName"></span></label>
                  <div class="col-md-4 col-lg-6 control-label" style="text-align: left;">
                    <label>共计号码数：<span id="totalNum">0</span>个，有效号码数：<span id="useNum">0</span>个(已过滤错误号码：<span id="errNum">0</span>个，已过滤重复号码<span id="reNum">0</span>个)</label>
                  </div>
                  <a class="btn btn-primary btn-sm" id="delSmsFile">删除</a>
                </div>
                <div class="form-group none" id="manual">
                  <label class="control-label col-sm-2">输入待发送手机号</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea class="form-control" style="height: 50px" name="phoneText" id="phoneText"></textarea> 
                  </div>
                </div>
              </div>
              <div id="xinBox" class="none">
                <div class="form-group">
                  <label class="control-label col-sm-2">号码归属地：</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <input name="area" type="text" class="form-control" placeholder="请输入号码归属地">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-2">号码数量：</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <input name="quantity" type="text" class="form-control" placeholder="请输入号码数量">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">选择模板</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <a class="btn btn-primary btn-sm" id="showTemplate">点击选择</a>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2 col-lg-2">短信类型</label>
                <div class="col-sm-1 col-lg-2">
                  <select class="form-control" name="smstype">
                    <option value="1" checked>验证码</option>
                    <option value="2">通知</option>
                    <option value="3">营销</option>
                  </select>
                </div>
                <label class="control-label col-sm-1">短信签名</label>
                <div class="col-md-2">
                  <input name="sign" type="text" class="form-control" placeholder="长度为2-8个字符" id="sign">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">短信内容</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea class="form-control" style="height: 100px" name="content" id="content"></textarea> 
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2">统计：</label>
                <label class="control-label col-sm-5" style="text-align: left;">内容长度计费条数:<span id="branch"></span>条 总计费条数:<span id="use"></span>条</label>
                <label class="control-label col-sm-2"><span id="num">0</span>/500</label>
              </div>
              <a class="btn btn-primary btn-sm col-sm-offset-2" id="sendBtn">发送</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="tempModal">
      <div class="modal-dialog modal-md"  style="width: 800px">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">模板列表</h4>
          </div>
          <div class="modal-body open-user-modal">
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>模板ID</th>
                  <th>模板属性</th>
                  <th>模板类型</th>
                  <th>模板内容</th>
                  <th>短信签名</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody id="templateTable">
              </tbody>
            </table>
            <div class="row">
              <div class="col-xs-6 col-left" >
                <div class="dataTables_info">总共<span id="dataTotal">0</span>条数据</div>
              </div>
              <div class="col-xs-6 col-right pagination-wrapper">
                <div class="dataTables_paginate paging_bootstrap pull-right">
                  <ul class="pagination pagination-sm" style="margin: 0px; padding: 0px;" id="pagetion">
<!--                     <li class="fa-hover none" id="pagePrev">
                      <a aria-label="Previous">
                        <i class="fa fa-chevron-left"></i>
                      </a>
                    </li>
                    <li class="fa-hover none" id="pageNext">
                      <a  aria-label="Next" class="i-height">
                        <i class="fa fa-chevron-right"></i>
                      </a>
                    </li> -->

                    <!-- <li class="pagination-li">
                      <sapn class="pagination-span-front">转到第</sapn><input class="pagination-input" name="inputPage" id="inputPage"><sapn class="pagination-span-back">页</sapn>
                      <a href="" class="btn btn-default pageButton" id="pagination-a">确定</a>
                    </li> -->
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/script/send/index.js"></script>
<?php $this->display("public/footer.phtml"); ?>