<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>发送记录</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-10">
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="请输入手机号">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="请输入内容">
                      </label>
                      <span>发送状态</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                            <option value="1">发送中</option>
                            <option value="2">发送失败</option>
                            <option value="3">发送成功</option>
                        </select>
                      </label>
                      <span>到达状态</span>
                      <label>
                        <select class="form-control input-sm">
                            <option value="0">全部</option>
                            <option value="1">发送中</option>
                            <option value="2">发送失败</option>
                            <option value="3">发送成功</option>
                        </select>
                      </label>
                      <div id="reportrange_right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc;display: inline-block;">
                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                        <span></span> <b class="caret"></b>
                      </div>
                    <a class="btn btn-primary btn-sm">
                      搜索
                    </a>
                  </div>
                  <div class="col-sm-2">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm">
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>序号</th>
                          <th>手机号</th>
                          <th>发送内容</th>
                          <th>发送状态</th>
                          <th>到达状态</th>
                          <th>状态码</th>
                          <th>发送时间</th>
                          <th>计费条数</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                            <td style="line-height: 34px">11</td>
                            <td style="line-height: 34px">11</td>
                            <td style="line-height: 34px">111</td>
                            <td style="line-height: 34px">111</td>
                            <td style="line-height: 34px">111</td>
                            <td style="line-height: 34px">111</td>
                            <td style="line-height: 34px">111</td>
                            <td style="line-height: 34px">111</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<?php $this->display("public/footer.phtml"); ?>