<?php $this->display("public/header.phtml", array()); ?>
  <?php $this->display("public/sidebar.phtml"); ?>
    <?php $this->display("public/nav.phtml"); ?>
      <div class="right_col" role="main">
        <div class="">
          <div class="row x_title">
            <div class="col-md-6">
              <h3>模板管理</h3>
            </div>
          </div>
          <div class="x_content">
            <div class="text-muted font-13 m-b-30">
              <div class="dataTables_wrapper dt-bootstrap no-footer">
                <div class="row">
                  <div class="col-sm-10">
                    <form class="search-form" method="get" action="">
                      <span>审核状态</span>
                      <label>
                        <select class="form-control input-sm" name="templateStatus">
                          <option value="0">全部</option>
                          <?php foreach ($this->templateStatus as $key =>$value):?>
                            <option value="<?php echo $key;?>" <?php echo $key==$this->status?'selected':'';?>><?php echo $value;?></option>
                          <?php endforeach;?>
                        </select>
                      </label>
                      <span>模板属性</span>
                      <label>
                        <select class="form-control input-sm" name="accounts">
                          <option value="0">全部</option>
                          <?php foreach ($this->accounts as $key =>$value):?>
                            <option value="<?php echo $key;?>" <?php echo $key==$this->classify?'selected':'';?>><?php echo $value;?></option>
                          <?php endforeach;?>
                        </select>
                      </label>
                      <span>模板类型</span>
                      <label>
                        <select class="form-control input-sm" name="types">
                          <option value="0">全部</option>
                          <?php foreach ($this->types as $key =>$value):?>
                            <option value="<?php echo $key;?>" <?php echo $key==$this->type?'selected':'';?>><?php echo $value;?></option>
                          <?php endforeach;?>
                        </select>
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="模板ID" name="tempid" value="<?php echo $this->tempid;?>">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="签名" name="sign" value="<?php echo $this->sign;?>">
                      </label>
                      <label>
                        <input type="text" class="form-control input-sm" placeholder="模板内容" name="content" value="<?php echo $this->content;?>">
                      </label>
                      <button type="submit" class="btn btn-primary btn-sm">搜索</button>
                    </form>
                  </div>
                  <div class="col-sm-2">
                    <div class="dataTables_filter">
                      <label>
                        <select class="form-control input-sm" id="selectPage">
                          <option value="15" <?php echo $pagelimit == 15? 'selected':''?>>15</option>
                          <option value="20" <?php echo $pagelimit == 20? 'selected':''?>>20</option>
                          <option value="50" <?php echo $pagelimit == 50? 'selected':''?>>50</option>
                          <option value="100" <?php echo $pagelimit == 100? 'selected':''?>>100</option>
                        </select>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>模板ID</th>
                          <th>模板属性</th>
                          <th>模板类型</th>
                          <th>模板内容</th>
                          <th>短信签名</th>
                          <th>创建时间</th>
                          <th>审核状态</th>
                          <th>原因</th>
                        </tr>
                      </thead>
                    <?php if(!empty($this->pager->getList())):?>
                      <?php $mapper = \Mapper\UsersModel::getInstance();?>
                      <?php foreach ($this->pager->getList() as $key=>$value):?>
                      <tbody>
                        <tr>
                          <td style="line-height: 34px"><?php echo $value['id'];?></td>
                          <td style="line-height: 34px"><?php echo $this->accounts[$value['classify']]?></td>
                          <td style="line-height: 34px"><?php echo $this->types[$value['type']]?></td>
                          <td style="line-height: 34px;overflow: hidden;width: 200px"><p style="width: 200px;cursor: pointer;white-space: nowrap; text-overflow: ellipsis;overflow: hidden;" class="showcontent"><?php echo $value['content']?></p></td>
                          <td style="line-height: 34px"><?php echo $value['sign']?></td>
                          <td style="line-height: 34px"><?php echo $value['created_at']?></td>
                          <td style="line-height: 34px"><?php echo $this->templateStatus[$value['status']]?></td>
                          <td style="line-height: 34px"><?php echo $value['reason']?></td>
                        </tr>
                      </tbody>
                      <?php endforeach;?>
                    <?php else:?>
                      <tbody>
                        <tr><td colspan="16">没有找到模板</td></tr>
                      </tbody>
                    <?php endif;?>
                    </table>
                    <?php echo $this->renderTpl('public/pagination.phtml',array(),'index');?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<?php $this->display("public/footer.phtml"); ?>